name: Deploy TRS System

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm run validate-system-health
      - run: npm run deploy-production
    {
    {
      version: 2
      updates:
   - package-ecosystem: "npm"
      directory: "/"
      schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "UTC"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "TRS SECURITY"
      prefix-development: "TRS DEV"
      include: "scope"
    reviewers:
      - "TRSAlliance/security-team"
    labels:
      - "trs-dependencies"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "05:00"
    reviewers:
      - "TRSAlliance/security-team"
    labels:
      - "trs-actions"
