# TRS SECURE DEPENDENCY UPDATE PROTOCOL v2.4
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "UTC"
    allow:
      - dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "TRS SECURITY"
      prefix-development: "TRS DEV"
    metadata:
      security: "high"
      trs-audit: "enforced"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
      time: "05:00"
    labels:
      - "trs-dependencies"
    reviewers:
      - "TRSAlliance/security-team"
