name: 🔄 TRS Secret Rotation
on:
  schedule:
    - cron: '0 0 1 * *'  # Monthly rotation
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-22.04
    environment: security
    steps:
      - uses: trs-alliance/rotate-secrets@v3
        with:
          key_type: quantum
          min_strength: 521
        env:
          KMS_KEY_ID: ${{ secrets.TRS_KMS_KEY }}
